FROM --platform=linux/amd64 golang:1.23-alpine AS builder
RUN apk add --no-cache protobuf protobuf-dev protobuf-c protobuf-c-dev
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN cd post-service/proto && \
    protoc --go_out=. --go_opt=module=social-network \
           --go-grpc_out=. --go-grpc_opt=module=social-network \
           *.proto

RUN CGO_ENABLED=0 GOOS=linux go build -o post-service ./post-service

FROM --platform=linux/amd64 alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/post-service .
EXPOSE 50052
CMD ["/app/post-service"]