# version: '3.8'

services:
  proxy-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./proxy-service/Dockerfile.simple
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - USER_SERVICE_URL=http://user-service:8000
    depends_on:
      - user-service
    networks:
      - social-network

  user-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./user-service/Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=socialnetwork
    depends_on:
      - postgres
    networks:
      - social-network

  postgres:
    platform: linux/amd64
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socialnetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  postgres-data:
